version: '3.8'

services:
  bob-helper-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - FLASK_ENV=development
      - PORT=8080
    volumes:
      # Mount source code for development (comment out for production)
      - ./happyLittleTreesOfKnowledge:/app:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: bob-helper-network